# -*- coding: utf-8 -*-
"""load_predict.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVpUoOn6-HvWt96kT-gqFw3gqc68Wzu4
"""

from keras.models import load_model
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.preprocessing import image
import numpy as np

model = tf.keras.models.load_model('/content/drive/MyDrive/nervousness_detection/best_model.h5')

# Define class labels
emotions = {0: 'fear', 1: 'neutral'}

# Load the test image
path = r'test.jpg'
img = load_img(path, target_size=(48,48))


# Preprocess the image
i = img_to_array(img) / 255
input_arr = np.array([i])

# Make prediction
pred = np.argmax(model.predict(input_arr))

# plot the image with the predicted class
import matplotlib.pyplot as plt
plt.imshow(img)
plt.title(f"The image is of {emotions[pred]}")
plt.show()


# Print the predicted class label
print(f"The image is of {emotions[pred]}")